export const products = [
    {
        id: 1,
        name: "chocolate doughnut",
        price: 1000,
        category: "Doughnuts",
        stock: 0,
    },
    {
        id: 2,
        name: "glazed doughnut",
        price: 1000,
        category: "Doughnuts",
        stock: 0,
    },
    {
        id: 3,
        name: "jam doughnut",
        price: 1000,
        category: "Doughnuts",
        stock: 0,
    },
    {
        id: 4,
        name: "red velvet cake",
        price: 2000,
        category: "Cake",
        stock: 0,
    },
    {
        id: 5,
        name: "chocolate cake",
        price: 2000,
        category: "Cake",
        stock: 0,
    },
    {
        id: 6,
        name: "vanilla cake",
        price: 2000,
        category: "Cake",
        stock: 0,
    },
    {
        id: 7,
        name: "meat pie",
        price: 500,
        category: "Pies",
        stock: 0,
    },
    {
        id: 8,
        name: "apple pie",
        price: 3000,
        category: "Pies",
        stock: 0,
    },
    {
        id: 9,
        name: "milkshake",
        price: 1500,
        category: "Drinks",
        stock: 0,
    },
    {
        id: 10,
        name: "coffee",
        price: 1200,
        category: "Drinks",
        stock: 0,
    },
    {
        id: 11,
        name: "diet coke",
        price: 1000,
        category: "Drinks",
        stock: 0,
    },
];
